# Local development: Postgres
services:
  postgres:
    image: postgres:16-alpine
    container_name: quote-service-postgres-dev
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: quote-service
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
